---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  duplication:
    enabled: true
    checks:
      Similar code:
          enabled: false
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
    exclude_fingerprints:
    - f8728cae8f316da8d60cd9fe03f658fd
    - 5d92a0498369d22fd35db5cc3684f29c
    - 1b4c600e85265b79c1f7ee140ff5c800
    - c5f08d507e17e0aed6c7c2e902f0a3e6
    - 901e29b7344cf9a1e550d2c27ce15ba3
    - 3ea75d20bf2a7ff7c1981cb051620e8e
    - 726e7aff89c9b155c325034be34ab400
    - 591358bcf34d89005d2adb0f73e395c3
    - 0a1abbc6557d2ad3a4848cf0e4e7ac02
    - f1259ddb555cc7f9253bd0dba0e4e076
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/AndOr:
        enabled: false
      Rubocop/Metrics/BlockLength:
        enabled: false
    exclude_fingerprints:
    - 2e796557124fc1e3127ee433626971a7
    - a3e1dbf8cb97a435038c8390306d8fdc
    - 5a391b75904ac294252a75cae95e977c
    - 67d765d44559fae66dcbfaf444e8929e
    - 312994113044146162fe57121c45a99e
    - 5fbe6043484b5fe2ff5491f75ff66581
    - 1064d189916e56f6eaabf8de6bfd429a
ratings:
  paths:
  - Gemfile.lock
  - "**.erb"
  - "**.haml"
  - "**.rb"
  - "**.rhtml"
  - "**.slim"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
exclude_paths:
- coverage/
- lib/templates
- config/
- db/
- spec/
- vendor/
- "app/assets/javascripts/multi_step_form.js"
- "app/assets/javascripts/bootstrap-switch.js"
- "app/assets/javascripts/bootstrap-select.min.js"
